all:
	sudo docker build -t inferx/inferx-bundle:v0.19.0-snd .

# docker run --gpus all -p 8000:8000 inferx/inferx-bundle:v0.1.0 \
# "python3 -m vllm.entrypoints.openai.api_server --model Qwen/Qwen3-Reranker-0.6B --port 8002" \
# "python3 -m vllm.entrypoints.openai.api_server --model Qwen/Qwen2.5-1.5B --port 8001"